export enum WeatherType {
  GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST',
  GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS',
  GET_WEATHER_FAIL = 'GET_WEATHER_FAIL'

  // ADD_HOTEL_REQUEST = 'ADD_HOTEL_REQUEST',
  // ADD_HOTEL_SUCCESS = 'ADD_HOTEL_SUCCESS',
  // ADD_HOTEL_FAIL = 'ADD_HOTEL_FAIL'
}
